### ISSUE TITLE
Missing parts for reproduction

### ISSUE THREAD

**Issue by gyuwankim** [ruoyuxie/recall#1]
Thank you for the great work and sharing the implementation!
I am trying to reproduce experimental results on the paper.
I found that the codes for the prefix ensemble and evaluation on MIMIR dataset are missing. 
Could you provide them for the exact reproduction if possible?

**Comment by ruoyuxie** [comment]
Hi Gyuwan, thank you for the question! 

The current codebase only contains a lightweight impelementation for WikiMIA dataset, but the evaluation process for MIMIR  dataset is _identical_ to the WikiMIA, and any datasets (including MIMIR) can be added to the pipeline through slight modification on `src/process_data.py`. 

For example, you could use MIMIR by modifying `create_dataset()` function using:
```
MIMIR_member = load_dataset("iamgroot42/mimir", f"{sub_dataset_names}")[f"ngram_{NGRAM}"]["member"]
MIMIR_nonmember = load_dataset("iamgroot42/mimir", f"{sub_dataset_names}")[f"ngram_{NGRAM}"]["nonmember"]
```
use `"arxiv", "dm_mathematics", "hackernews", "github" ...` for `sub_dataset_names` and `"13_0.8"` or `"7_0.2"` for `NGRAM` to retrieve the exact sub-dateset from MIMIR that you would like to use. 

For ensemble, you can call the following function from `inference()` from `src/run.py`:

```
def ensemble_inference(pred, text, model1, tokenizer1, member_demonstrations, nonmember_demonstrations, k):
    # If the total shot is 28, k is 7, then the number of examples per each group will be 4
    N = min(len(member_demonstrations), len(nonmember_demonstrations)) // k
    total_ll_nonmember = []
    ensemble_preds = []
    ll = get_ll(text, model1, tokenizer1, accelerator.device)[0]
    for i in range(k):
        start_idx = i * N
        end_idx = (i + 1) * N
        # Create smaller group with N examples
        group_nonmember_demos = nonmember_demonstrations[start_idx:end_idx]
        _, ll_nonmember, _, all_prob_nonmember,_ = get_conditional_ll("".join(group_nonmember_demos), text, model1, tokenizer1, accelerator.device)
        total_ll_nonmember.append(ll_nonmember)
    pred["avg_llnm_recall"] = np.mean(total_ll_nonmember) / ll 
```
tune the number of `k` based on the model you use. 

Hope this helps!

**Comment by gyuwankim** [comment]
Hi Roy, thank you very much for the prompt reply! It looks helpful. I will apply and come back if I have a further question.
